import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/About.module.css";

//images
import ContentFolder from "../images/ContentFolder.png";
import OurStory1 from "../images/OurStory1.png";
import OurStory2 from "../images/OurStory2.png";

//icons
import { Email, LocationOn } from "@mui/icons-material";

//components
import AnimatedImage from "../components/AnimatedImage";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Taranberg</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.section__1}>
          <div
            style={{
              width: "300px",
              height: "300px",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <Image src={ContentFolder} alt="ContentFolder" />
          </div>
          <h1 className={styles.title}>About Taranberg</h1>
          <p className={styles.description}>
            Driving your business forward with strong educational content.
          </p>
        </section>

        <section className={styles.section__2}>
          <h1 className={styles.title__sub}>Our Story</h1>
          <p className={styles.description}>
            Founded in 2022, Taranberg’s mission is to help businesses and{" "}
            <br></br>
            people express the value of their products.
          </p>
          <div style={{ height: "100px" }} />
          <div className={styles.section__2__content}>
            <div className={styles.section__2__content__sub}>
              <div className={styles.image__container}>
                <AnimatedImage direction="left">
                  <Image src={OurStory1} alt="OurStory1" />
                </AnimatedImage>
              </div>
              <div className={styles.description__container}>
                <p className={styles.section__2__desctiption}>
                  Whether it's doing thorough research or writing remarkable
                  text and then giving it a unique design, Taranberg wants to
                  make sure your business stands out in your field. As such, we
                  create content that people love around the globe.
                </p>
              </div>
            </div>
            <div className={styles.section__2__content__sub}>
              <div className={styles.description__container}>
                <p className={styles.section__2__desctiption}>
                  Whether it's doing thorough research or writing remarkable
                  text and then giving it a unique design, Taranberg wants to
                  make sure your business stands out in your field. As such, we
                  create content that people love around the globe.
                </p>
              </div>
              <div className={styles.image__container}>
                <AnimatedImage direction="right">
                  <Image src={OurStory2} alt="OurStory2" />
                </AnimatedImage>
              </div>
            </div>
          </div>
        </section>

        <section className={styles.section__3}>
          <h1 className={styles.title}>Solutions</h1>
          <p className={styles.description}>
            Our team focuses on three key problems:
          </p>

          <div className={styles.section__3__content}>
            <div className={styles.section__3__content__sub}>
              <div className={styles.section__3__content__sub__icon__1}>1</div>
              <p className={styles.section__3__desctiption}>
                Finding the best <br></br> products out there.
              </p>
            </div>
            <div className={styles.section__3__content__sub}>
              <div className={styles.section__3__content__sub__icon__2}>2</div>
              <p className={styles.section__3__desctiption}>
                Successfully get them in <br></br> front of the right people.
              </p>
            </div>
            <div className={styles.section__3__content__sub}>
              <div className={styles.section__3__content__sub__icon__3}>3</div>
              <p className={styles.section__3__desctiption}>
                Helping businesses grow <br></br> the right way.
              </p>
            </div>
          </div>

          <p className={styles.section__3__desctiption}>
            Through unique content, beautiful design, and precise accessibility,
            Taranberg takes the creation of <br></br> educational content to the
            extreme and helps everyone get better materials online.
          </p>
        </section>

        <section className={styles.section__4}>
          <h1 className={styles.title__sub}>Our Location</h1>
          <div style={{ height: "80px" }} />
          <div className={styles.section__4__content}>
            <div className={styles.section__4__content__sub}>
              <div className={styles.description__container}>
                <h1 className={styles.title__sub__2}>Tel Aviv</h1>
                <div className={styles.icon__container}>
                  <LocationOn style={{ marginRight: "10px" }} />
                  <p className={styles.section__4__desctiption}>
                    Aluf Kalman Magen St 3, Tel Aviv-<br></br>Yafo, 6107075,
                    Israel
                  </p>
                </div>
                <div className={styles.icon__container}>
                  <Email style={{ marginRight: "10px" }} />
                  <p className={styles.section__4__desctiption}>
                    hello@taranberg.com
                  </p>
                </div>
              </div>
              <div className={styles.image__container}>
                <AnimatedImage direction="right">
                  <iframe
                    width="512"
                    height="404"
                    id="gmap_canvas"
                    src="https://maps.google.com/maps?q=Aluf%20Kalman%20Magen%20St%203,%20Tel%20Aviv-Yafo,%206107075,%20Israel&t=&z=15&ie=UTF8&iwloc=&output=embed"
                    scrolling="no"
                  ></iframe>
                </AnimatedImage>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
